my_project/src/Entity/Comment.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommentRepository")
 */
class Comment
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Page", inversedBy="comment")
     * @ORM\JoinColumn(nullable=false)
     */
    private $page;

    /**
     * @ORM\Column(type="date")
     */
    private $CreationDate;

    /**
     * @ORM\Column(type="text")
     */
    private $text;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPage(): ?Page
    {
        return $this->page;
    }

    public function setPage(?Page $page): self
    {
        $this->page = $page;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->CreationDate;
    }

    public function setCreationDate(\DateTimeInterface $CreationDate): self
    {
        $this->CreationDate = $CreationDate;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }
}

my_project/src/Entity/Teacher.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TeacherRepository")
 */
class Teacher
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=100, unique=true)
     */
    private $email;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\TeacherClasses", mappedBy="teacher")
     */
    private $teacherClasses;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Subject")
     */
    private $subjects;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $teacher_code;

    public function __construct()
    {
        $this->teacherClasses = new ArrayCollection();
        $this->subjects = new ArrayCollection();
        $this->teacherSurveyMarks = new ArrayCollection();
        $this->groups = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return Collection|TeacherClasses[]
     */
    public function getTeacherClasses(): Collection
    {
        return $this->teacherClasses;
    }

    public function addTeacherClass(TeacherClasses $teacherClass): self
    {
        if (!$this->teacherClasses->contains($teacherClass)) {
            $this->teacherClasses[] = $teacherClass;
            $teacherClass->setTeacher($this);
        }

        return $this;
    }

    public function removeTeacherClass(TeacherClasses $teacherClass): self
    {
        if ($this->teacherClasses->contains($teacherClass)) {
            $this->teacherClasses->removeElement($teacherClass);
            // set the owning side to null (unless already changed)
            if ($teacherClass->getTeacher() === $this) {
                $teacherClass->setTeacher(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|subject[]
     */
    public function getSubjects(): Collection
    {
        return $this->subjects;
    }

    public function addSubject(subject $subject): self
    {
        if (!$this->subjects->contains($subject)) {
            $this->subjects[] = $subject;
        }

        return $this;
    }

    public function removeSubject(subject $subject): self
    {
        if ($this->subjects->contains($subject)) {
            $this->subjects->removeElement($subject);
        }

        return $this;
    }

   

    

    public function getTeacherCode(): ?string
    {
        return $this->teacher_code;
    }

    public function setTeacherCode(string $teacher_code): self
    {
        $this->teacher_code = $teacher_code;

        return $this;
    }
}

my_project/src/Form/TeacherType.php
<?php

namespace App\Form;

use App\Entity\User;
use App\Entity\Subject;
use App\Entity\Teacher;
use App\Entity\School;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;


//Form to create a new teacher.
class TeacherType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('lastname')
            ->add('firstname')
            ->add('email')
            ->add('gender', ChoiceType::class, [
                'choices'  => [
                    'Male' => 'male',
                    'Female' =>'female'
                ],
                'expanded' => true,
                'multiple' =>false
            ])
            ->add('password', PasswordType::class)
            ->add('confirm_password', PasswordType::class)
            ->add('subjects',EntityType::class,
            [
                'class' => Subject::class,
                'choice_label' => 'name',
                'expanded' => false,
                'multiple' =>true,
                'mapped' =>false
            ])
            ->add('school',EntityType::class,
                   [ 'class'=>School::class,
                    'choice_label'=>'name'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

my_project/src/Controller/TeacherController.php
<?php

namespace App\Controller;

use App\Entity\Page;
use App\Entity\Sheet;
use App\Entity\Subject;
use App\Entity\Teacher;
use App\Service\EmailService;
use App\Service\TeacherService;
use App\Repository\PageRepository;
use App\Repository\SchoolRepository;
use App\Repository\CommentRepository;
use App\Repository\SubjectRepository;
use App\Repository\TeacherClassesRepository;
use App\Repository\TeacherPageMarkRepository;
use Symfony\Component\HttpFoundation\Request;
use App\Repository\TeacherSurveyMarkRepository;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class TeacherController extends AbstractController
{
    /**
    * @Route("/teacher/", name="teacher")
    */
    public function index(Request $request, CommentRepository $commentRepository,TeacherClassesRepository $teacherClassesRepository, TeacherPageMarkRepository $teacherPageMarkRepository, TeacherService $teacherService,PageRepository $pageRepository)
    {   
    
        //Main page of a teacher


        //Web page to select the survey that the teacher want to see more detail 
if(!$request->request->get('page_selected')){


        $teacher = ($this->getUser()->getUserTeacher())->getTeacher();

        $date = new \DateTime();
        $year = $date->format('Y');
      $surveyList = $teacherService->getSurveysForTeacher($teacher,$year);
      
      $data=$teacherService->getPageBySurveys($surveyList, $teacher);

      
      return $this->render('/teacher/pre.index.form.html.twig',['data'=> $data]);
       
}else{
  //Web page to display  infomation about a survey (marks , comments , statistics ...)
  $teacher = ($this->getUser()->getUserTeacher())->getTeacher();
  $page    = $pageRepository->find($request->request->get('page_selected'));
  $marklist =$teacherService->getMarkListofTeacherForOnePage($page);
  $mark  =$teacherPageMarkRepository->findOneByTeacherAndPage($teacher,$page);

        
  $teacherClassesList = $teacher->getTeacherClasses();
  $school = $this->getUser()->getSchool();

  
  $commentnumber = $commentRepository->countByPage($page);
  $randomcomment = $commentRepository->findOneByPage($page);
  dump($mark);
  dump($marklist);
if(!$mark){
    return $this->render('teacher/error_pages/error.not.found.mark.html.twig');
}
$graphdata = $teacherService->getMarksTeacherMainGraph($teacher,$page);
  return $this->render('teacher/index.html.twig', ['pageId'=>$page->getId(),
      'commentnumber' => $commentnumber, 'controller_name' => 'TeacherController', 'mark' => $mark, 'marklist' => $marklist, 'school' => $school, 'teacher' => $teacher, 'teacherClassesList' => $teacherClassesList, 'randomcomment'=>$randomcomment, 'graphdata'=>$graphdata]);
  
}      
  }
  
	/**
    * @Route("/teachercz/", name="teachercz")
    */
    public function indexcz(Request $request, CommentRepository $commentRepository,TeacherClassesRepository $teacherClassesRepository, TeacherPageMarkRepository $teacherPageMarkRepository, TeacherService $teacherService,PageRepository $pageRepository)
    {   
    
        //Main page of a teacher
if(!$request->request->get('page_selected')){


        $teacher = ($this->getUser()->getUserTeacher())->getTeacher();

        $date = new \DateTime();
        $year = $date->format('Y');
      $surveyList = $teacherService->getSurveysForTeacher($teacher,$year);
      
      $data=$teacherService->getPageBySurveys($surveyList, $teacher);

      
      return $this->render('/teacher/pre.index.formcz.html.twig',['data'=> $data]);
       
}else{
  //Get infomation about a survey
  $teacher = ($this->getUser()->getUserTeacher())->getTeacher();
  $page    = $pageRepository->find($request->request->get('page_selected'));
  $marklist =$teacherService->getMarkListofTeacherForOnePage($page);
  $mark  =$teacherPageMarkRepository->findOneByTeacherAndPage($teacher,$page);

        
  $teacherClassesList = $teacher->getTeacherClasses();
  $school = $this->getUser()->getSchool();

  
  $commentnumber = $commentRepository->countByPage($page);
 
  if(!$mark || !$marklist){
    return $this->render('teacher/error_pages/error.not.found.markcz.html.twig');
}

  return $this->render('teacher/indexcz.html.twig', ['pageId'=>$page->getId(),
      'commentnumber' => $commentnumber, 'controller_name' => 'TeacherController', 'mark' => $mark, 'marklist' => $marklist, 'school' => $school, 'teacher' => $teacher, 'teacherClassesList' => $teacherClassesList]);
  
}      
  }


    /**
     *@Route("teacher/stats/{id}", name="teacher_stats")
     */
    public function showStats(Page $page,CommentRepository $commentRepository, SubjectRepository $subjectRepository,Request $request)
    { //Show the stats of a teacher
        $teacher = ($this->getUser()->getUserTeacher())->getTeacher();
        

       

        if($request->request->get('class_selection'))
        {
            $classId=$request->request->get('class_selection');
            $classes= $classesRepository->find($classId);
            $comments =  $commentRepository->findByClasses($classes);
            return $this->render('teacher/stats.details.html.twig', ['pageId'=>$page->getId(),'teacher' => $teacher, 'classes' => $classes, 'subject' => null, 'comments'=>null]);
        }
        
        elseif($request->request->get('subject_selection')){
            $subjectId=$request->request->get('subject_selection');
            $subject = $subjectRepository->find($subjectId);
            return $this->render('teacher/stats.details.html.twig', ['pageId'=>$page->getId(),'teacher' => $teacher, 'classes' => $classes, 'subject' => null, 'comments'=>null]);

        }
         
            $comments = $commentRepository->findByPage($page);
            $commentnumber = $commentRepository->countByPage($page);

            return $this->render('teacher/stats.details.html.twig', ['pageId'=>$page->getId(),'commentnumber' => $commentnumber, 'teacher' => $teacher, 'classes' => null, 'subject' => null,'comments'=>$comments]);
       
        
        
    }

    /**
    *@Route("teacher/rating/{id}", name="school_rating")
    */
    public function SchoolSatisfyingRating(Page $page,TeacherService $teacherService,SchoolRepository $schoolRepository, TeacherPageMarkRepository $teacherPageMarkRepository)
    {    //See the Statistics of a school
        $school = $this->getUser()->getSchool();
        $schools = $schoolRepository->findAll();

        $marklist =$teacherService->getMarkListofTeacherForOnePage($page);
        $mark = $teacherPageMarkRepository->findOneByPage($page);

        return $this->render('teacher/school.satisfying.html.twig',
        ['school' => $school, 'schools' => $schools, 'mark' => $mark, 'marklist' => $marklist]);
    }

    /**
     * @Route("teacher/send/email/{id}", name="teacher_send_email")
     */
    public function senMail(Page $page,TeacherPageMarkRepository $teacherPageMarkRepository, EmailService $emailService, \Swift_Mailer $mailer){
        $teacher =$page->getTeacher();
        $teacherPageMark =$teacherPageMarkRepository->findOneByPage($page);
        $messageText = 'Teacher Information'."\n"
        .'-------------------------------------------------------------'."\n"
        . 'Teacher: '.$teacher->getFirstName().' '.$teacher->getLastName()."\n"
        .'Subject :'.$page->getSubject()->getName()."\n"
        .'Class : '.(($page->getSheet())->getClasses())->getName()."\n"
        .'School :'.((($page->getSheet())->getClasses())->getSchool())->getName()."\n"
        
        . '-------------------------------------------------------------'."\n"
        . 'Your mark: '.$teacherPageMark->getMark()."\n"
       
        . 'You have received feedback from: '.$teacherPageMark->getNumberOfResponses().' people'."\n"
        . '-------------------------------------------------------------'."\n";
    
    
        ;
        $email=$teacher->getEmail();
        $emailService->sendEmailtoTeacher($messageText,'kevinpizeuil@gmail.com',$mailer);
    return $this->render('test/hello.world.html.twig');
    }

    /**
     *@Route("chart" , name="chart")
     */
    public function chart(TeacherService $teacherService,PageRepository $pageRepository){
 $page= $pageRepository->find(51);
 $teacher=$page->getTeacher();
 $data = $teacherService->getMarksTeacherMainGraph($teacher,$page);
        return $this->render('test/chart.html.twig', ['data'=> $data]);
    }
}

my_project/templates/teacher/index.html.twig
{% extends 'basecz.html.twig' %}
{% block title %} Teacher Page {% endblock %}
{% block navBar %}
<li class="nav-item">
<a class="nav-link" href="">{{app.user.lastname}}  {{app.user.firstname}}</a>
</li>
<li class="nav-item">
<a class="nav-link" href="{{path('school_rating',{'id':pageId})}}"> Schools Satisfying Rating </a>
</li>
{% endblock %}



{% block javascripts %}

<!-- JavaScript starts here -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/highcharts-3d.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.5/jspdf.debug.js"></script>
<script src="https://code.highcharts.com/modules/histogram-bellcurve.js"></script>

<script>

function email()
{
    alert("The letter was sent to: {{teacher.email}}");
    var link = "mailto:{{teacher.email}}"
             + "?cc=myCCaddress@example.com"
             + "&subject=" + escape("This is my subject")
             + "&body=" + escape(document.getElementById('myText').value)
    ;
    window.location.href = link;
}

function exportPDF()
{
    // Default export is a4 paper, portrait, using milimeters for units
    var doc = new jsPDF();
    doc.text('Teacher Information.\n'
    + '-------------------------------------------------------------\n'
    + 'Teacher: {{teacher.firstname}} {{teacher.lastname}}.\n'
    + 'Subject: {% for tc in teacherClassesList %}{{tc.subject.name}}{% endfor %}.\n'
    + 'Group: 5A. \n'
    + 'Classes: {% for tc in teacherClassesList %}{{tc.classes.name}}{% endfor %}.\n'
    + 'School: {{school.name}}.\n'
    + 'E-mails: {{teacher.email}}.\n'
    + '-------------------------------------------------------------\n'
    + 'Your mark: {{mark.mark}}.\n'
    + 'Comments about you: {{commentnumber}}.\n'
    + 'You have received feedback from: {{mark.numberOfResponses}} people.\n'
    + '-------------------------------------------------------------\n', 10, 10);

    doc.save('INFO_{{teacher.firstname}}{{teacher.lastname}}.pdf');
}

function exportPDFTwo()
{
    Highcharts.charts[0].exportChart({type: 'application/pdf'});
}


</script>

<!-- JavaScript ends here -->

{% endblock %}

{% block body %}

	<div class="row">
		<div class="col-3" style="margin-top:10px; margin-left:25px;">
			<!-- Sidebar  -->
        <div class="container" style="background-color:#17a2b8;">    
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3>Statistics</h3>
            </div>

            <ul class="list-unstyled components">
                <p><b>{{teacher.firstname}} {{teacher.lastname}}</b></p>
				<li>
					<a href="{{path('teachercz')}}" style="color:#000;" ><img src="https://i.ibb.co/MZkhJ82/cz.png"></img>Czech Version</a>
				</li>
                <li>
                    <a href="{{path('teacher_send_email',{'id':pageId})}}" style="color:#c2e59c;" onClick="email()">Send results to E-mail</a>
                </li>

                <li>
                    <a href="#" style="color:#c2e59c;" onClick="exportPDF()">Export info as PDF document</a>
                </li>
                <li>
                    <a href="#" style="color:#c2e59c;" onClick="exportPDFTwo()">Export graphics as a PDF document</a>
                </li>
								<li>
										<a href="#" style="color:#c2e59c;" onClick="showMarks()">My graphics</a>
								</li>
								<li>
										<a href="#" style="color:#c2e59c;" onClick="showTeach()">Other teacher graphics</a>
								</li>
            </ul>

            <ul class="list-unstyled CTAs">
                <li>
                    <a href="" style="color:#000;" onclick="window.location.href='{{ path('security_logout') }}'" class="download">Logout</a>
                </li>
            </ul>
        </nav>
		</div>
        </div>
		<div class="col-7" style="margin-right:80px; width: 90%;">

			<div class="row">
				<div class="container" style="margin-top:10px;">
					<h3 class="display-4">▪ Teacher Information ▪</h3>
					<hr>
					<h4>&nbsp;<b>Firstname:</b> {{teacher.firstname}} {{teacher.lastname}} </h4>
					<h4>&nbsp;<b>Subject:</b>{% for tc in teacherClassesList %}
							{{tc.subject.name}}
					{% endfor %} </h4>
					<h4>&nbsp;<b>Group:</b> 5A</h4>
					<h4>&nbsp;<b>Classes:</b> {% for tc in teacherClassesList %}
							{{tc.classes.name}}
					{% endfor %} </h4>
					<h4>&nbsp;<b>School:</b> {{school.name}}</h4>
					<h4>&nbsp;<b>E-mail:</b> {{teacher.email}} </h4>
					
				</div>




			</div>
            <div class="row">
            				<div class="container" style="margin-top:10px;">
				    <h3 class="display-4"> Last comments </h3>
				    <hr>
				    <section>
				        <h4>Comment <b> {{commentnumber}} </b> :</h4>
                        {% if randomcomment %}
                         <div>{{randomcomment.creationDate|date('Y/m/d')}}</div>
				        <p>{{randomcomment.text}}</p>
                        {% endif %}
				    </section>
						<div align="center"><button onclick="location.href='{{path('teacher_stats',{'id':pageId})}}'" type="button" class="submit"> Show all comments </button></div>
				</div>
            
			</div>

	    </div>


    </div>
<div class="row" style="margin-top:20px;">

<div id="chartContainer" style="margin-left:80px; width: 90%;">	</div>
</div>
<script>
window.onload = function () {

var chart = new CanvasJS.Chart("chartContainer", {
	animationEnabled: true,
	theme: "light2", 
	title:{
		text: "How your students response"
	},
	axisY: {
		title: "Subject"
	},
	data: [{        
		type: "column",  
		showInLegend: true, 
		legendMarkerColor: "grey",
		legendText: "Mark",
		dataPoints:{{ graphdata|json_encode|raw }}       
    
	}]
});
chart.render();

}
</script>
<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>


{% endblock %}

my_project/templates/teacher/pre.index.form.html.twig
{% extends "base.html.twig" %}
{% block body %}
<br>
<div class="container">
<b><h2 align="center" style="color:#007AFF">List of survey you have: </h2></b>
<div align="center"><a href="{{path('teachercz')}}"><img src="https://i.ibb.co/ZftRzPq/cz.png"></img> Czech version</a></div>
<hr>
<form action="{{path('teacher')}}" method="post">
{% for dt in data %}
<h3 style="color:#007AFF">{{dt.survey.title}}</h3>
<table class="table">
<tr>
    <th>Survey</th>
    <th>Class</th>
    <th>Subject</th>
</tr>
{% for page in dt.pages %}
    <tr>
    <td>{{dt.survey.id}}</td>
    <td>{{dt.survey.classes.name}}</td>

      <td>
    <input type="radio" class="rButton" name="page_selected"  value="{{page.id}}"/>
    <span class="convText">{{page.subject.name}}</span>
</td>

</tr>
{% endfor %}
</table>
{% endfor %}
<div class="form-textbox">
      <input type="submit" name="submit" id="submit" class="submit" value="Select" />
  </div>
</form>
</div>
{% endblock %}

my_project/templates/teacher/pre.index.formcz.html.twig
{% extends "basecz.html.twig" %}
{% block body %}
<br>
<div class="container">
<b><h2 align="center" style="color:#007AFF">Seznam průzkumu, který máte: </h2></b>
<div align="center"><a href="{{path('teacher')}}"><img src="https://i.ibb.co/MZkhJ82/uk.png"></img> English version</a></div>
<hr>
<form action="{{path('teachercz')}}" method="post">
{% for dt in data %}
<h3 style="color:#007AFF">{{dt.survey.title}}</h3>
<table class="table">
<tr>
    <th>Průzkum</th>
    <th>Třída</th>
    <th>Předmět</th>
</tr>
{% for page in dt.pages %}
    <tr>
    <td>{{dt.survey.id}}</td>
    <td>{{dt.survey.classes.name}}</td>
    <td>{{page.subject.name}}</td>
    <td><div class="form-check">
          <input class="form-check-input" type="radio" name="page_selected"  value="{{page.id}}">
        </div></td>
</tr>
{% endfor %}
</table>
{% endfor %}
<div class="form-textbox">
      <input type="submit" name="submit" id="submit" class="submit" value="Vybrat" />
  </div>

</form>
</div>
{% endblock %}

my_project/templates/teacher/school.satisfying.html.twig
{% extends 'base.html.twig' %}
{% block title %} School Satisfying {% endblock %}
{% block navBar %}
<li class="nav-item">
<a class="nav-link" href="">{{app.user.lastname}}  {{app.user.firstname}}</a>
</li>
<li class="nav-item">
<a class="nav-link" href="{{path('school_rating')}}"> Schools Satisfying Rating </a>
</li>
{% endblock %}


{% block javascripts %}

<!-- JavaScripts starts here -->

<script>

function sortTable(n)
{
  var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
  table = document.getElementById("myTable");
  switching = true;
  dir = "asc";
  while (switching)
  {
    switching = false;
    rows = table.rows;
    for (i = 1; i < (rows.length - 1); i++)
    {
      shouldSwitch = false;
      x = rows[i].getElementsByTagName("TD")[n];
      y = rows[i + 1].getElementsByTagName("TD")[n];
      if (dir == "asc")
      {
        if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
          //if so, mark as a switch and break the loop:
          shouldSwitch= true;
          break;
        }
      }
      else if (dir == "desc")
      {
        if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase())
        {
          shouldSwitch = true;
          break;
        }
      }
    }
    if (shouldSwitch)
    {
      rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
      switching = true;
      switchcount ++;
    }
    else
    {
      if (switchcount == 0 && dir == "asc")
      {
        dir = "desc";
        switching = true;
      }
    }
  }
}

</script>

<!-- JavaScripts ends here -->

{% endblock %}

{% block body %}
{% set TM = 14.7 %}

<div align="center">

<h1> Page for School Ratings</h1>

<table id="myTable" border="1">
<tr>
    <th class="tablestart">
        <h3> ID: </h3>
    </th>
    <th class="tablestart">
        <h3> School name: </h3>
    </th>
    <th onclick="sortTable(0)" class="tablestart">
        <h3> Teacher marks: </h3>
    </th>
    <th onclick="sortTable(1)" class="tablestart">
        <h3><b> TOTAL: </b></h3>
    </th>
</tr>
{% for sch in schools %}
<tr>
    <td>
        <h3> {{ sch.id }} </h3>
    </td>
    <td>
        <h3> {{ sch.name }} </h3>
    </td>
    <td>
        <h3>
        {% for mrk in marklist %}
            {% if sch.id == mrk.id %}
            {{ mrk.mark }}
            {% endif %}
        {% endfor %}
        </h3>
    </td>
    <td>
        <h3>
            {% for mrk in marklist %}
            {% if sch.id == mrk.id %}
            {{ mrk.mark * 20 }} %
            {% endif %}
        {% endfor %}
        </h3>
    </td>
</tr>
{% endfor %}
</table>

<br>
<button onClick="" type="button"> Show Satisfying Graph </button>

</div>

{% endblock %}